### ISSUE TITLE
Color not showing

### ISSUE THREAD

**Issue by harshit23897** [CaptainDaVinci/Tic-Tac-Toe#1]
The output is not showing color.

**Comment by CaptainDaVinci** [comment]
Which operating system did you use? 
The coloured output should be working on both Windows as well as Linux ?

**Comment by harshit23897** [comment]
Windows 7. Okay I checked ,it is working fine on ubuntu.

**Comment by CaptainDaVinci** [comment]
But, it should also work for windows. 
Have you tried replacing
 `system("clear");` with `system("cls")`; ? 
I have observed that if you comment out the clear command, it does not work as expected on windows. But if you replace it with cls, it works.
